namespace GLUELib;

public static class Constants
{
  // Message descriptions
  public static readonly string[][] MessageDescriptions = [
    // S0 - Abstract Stream
    [],

    // S1 - Tool Status
    [
      "Not On Line",
      "Are You There?",
      "On Line Data",
      "Selected Equipment Status Request",
      "Selected Equipment Status Data",
      "Formatted Status Request",
      "Formatted Status Data",
      "Fixed Form Request",
      "Fixed Form Data",
      "Material Transfer Status Request",
      "Material Transfer Status Data",
      "Status Variable Namelist Request",
      "Status Variable Namelist Reply",
      "Establish Communications Request",
      "Establish Communications Request Acknowledge",
      "Request OFF-LINE",
      "OFF-LINE Acknowledge",
      "Request ON-LINE",
      "ON-LINE Acknowledge",
      "Get Attribute",
      "Attribute Data",
      "Data Variable (DVVAL) Namelist Request",
      "Data Variable (DVVAL) Namelist Reply",
      "Collection Event Namelist Request",
      "Collection Event Namelist Reply",
    ],

    // S2 - Tool Control & Diagnostics
    [
      "Abort Transaction",
      "Service Program Load Inquire",
      "Service Program Load Grant",
      "Service Program Send",
      "Service Program Send Acknowledge",
      "Service Program Load Request",
      "Service Program Load Data",
      "Service Program Run Send",
      "Service Program Run Acknowledge",
      "Service Program Results Request",
      "Service Program Results Data",
      "Service Program Directory Request",
      "Service Program Directory Data",
      "Equipment Constant Request",
      "Equipment Constant Data",
      "New Equipment Constant Send",
      "New Equipment Constant Ack",
      "Date and Time Request",
      "Date and Time Data",
      "Reset/Initialize Send",
      "Reset Acknowledge",
      "Remote Command Send",
      "Remote Command Acknowledge",
      "Trace Initialize Send",
      "Trace Initialize Acknowledge",
      "Loopback Diagnostic Request",
      "Loopback Diagnostic Data",
      "Initiate Processing Request",
      "Initiate Processing Acknowledge",
      "Equipment Constant Namelist Request",
      "Equipment Constant Namelist",
      "Date and Time Set Request",
      "Date and Time Set Acknowledge",
      "Define Report",
      "Define Report Acknowledge",
      "Link Event Report",
      "Link Event Report Acknowledge",
      "Enable/Disable Event Report",
      "Enable/Disable Event Report Acknowledge",
      "Multi-block Inquire",
      "Multi-block Grant",
      "Host Command Send",
      "Host Command Acknowledge",
      "Configure Spooling",
      "Configure Spooling Acknowledge",
      "Define Variable Limit Attributes",
      "Define Variable Limit Attributes Acknowledge",
      "Variable Limit Attribute Request",
      "Variable Limit Attribute Send",
      "Enhanced Remote Command",
      "Enhanced Remote Command Acknowledge",
      "Query Report Identifiers",
      "Return Report Identifiers",
      "Query Report Definitions",
      "Return Report Definitions",
      "Query Report Links",
      "Return Report Links",
      "Query Enabled Events",
      "Return Enabled Events",
      "Query Spool Streams and Functions",
      "Return Spool Streams and Functions",
      "Query Trace Identifiers",
      "Return Trace Identifiers",
      "Query Trace Definitions",
      "Return Trace Definitions",
    ],

    // S3 - Material Status
    [
      "Abort Transaction",
      "Material Status Request",
      "Material Status Data",
      "Time to Completion Request",
      "Time to Completion Data",
      "Material Found Send",
      "Material Found Ack",
      "Material Lost Send",
      "Material Lost Ack",
      "Matl ID Equate Send",
      "Matl ID Equate Ack",
      "Matl ID Request",
      "Matl ID Request Ack",
      "Matl ID Send",
      "Matl ID Ack",
      "Matls Multi-block Inquire",
      "Matls Multi-block Grant",
      "Carrier Action Request",
      "Carrier Action Ack",
      "Cancel All Carrier Out Req",
      "Cancel All Carrier Out Ack",
      "Port Group Defn",
      "Port Group Defn Ack",
      "Port Group Action Req",
      "Port Group Action Ack",
      "Port Action Req",
      "Port Action Ack",
      "Change Access",
      "Change Access Ack",
      "Carrier Tag Read Req",
      "Carrier Tag Read Data",
      "Carrier Tag Write Data",
      "Carrier Tag Write Ack",
      "Cancel All Pod Out Req",
      "Cancel All Pod Out Ack",
      "Reticle Transfer Job Req",
      "Reticle Transfer Job Ack",
    ],

    // S4 - Material Control
    [
      "Abort",
      "Ready to Send Materials",
      "Ready to Send Ack",
      "Send Material",
      "",
      "Handshake Complete",
      "",
      "Not Ready To Send",
      "",
      "Stuck in Sender",
      "",
      "Stuck in Receiver",
      "",
      "Send Incomplete Timeout",
      "",
      "Material Received",
      "",
      "Request to Receive",
      "Request to Receive Ack",
      "Transfer Job Create",
      "Transfer Job Acknowledge",
      "Transfer Job Command",
      "Transfer Job Command Ack",
      "Transfer Command Alert",
      "Transfer Alert Ack",
      "Multi-block Inquire",
      "Multi-block Grant",
      "Handoff Ready",
      "",
      "Handoff Command",
      "",
      "Handoff Command Complete",
      "",
      "Handoff Verified",
      "",
      "Handoff Cancel Ready",
      "",
      "Handoff Cancel Ready Ack",
      "",
      "Handoff Halt",
      "",
      "Handoff Halt Ack",
    ],

    // S5 - Exception Handling
    [
      "Abort Transaction",
      "Alarm Report Send",
      "Alarm Report Ack",
      "Enable/Disable Alarm Send",
      "Enable/Disable Alarm Ack",
      "List Alarms Request",
      "List Alarms Data",
      "List Enabled Alarms Request",
      "List Enabled Alarms Data",
      "Exception Post Notify",
      "Exception Post Confirm",
      "Exception Clear Notify",
      "Exception Clear Confirm",
      "Exception Recovery Request",
      "Exception Recovery Acknowledge",
      "Exception Recovery Complete Notify",
      "Exception Recovery Complete Confirm",
      "Exception Recovery Abort Request",
      "Exception Recovery Abort Ack",
    ],

    // S6 - Data Collection
    [
      "Abort Transaction",
      "Trace Data Send",
      "Trace Data Ack",
      "Discrete Variable Data Send",
      "Discrete Variable Data Send Ack",
      "Multi-block Data Send Inquire",
      "Multi-block Grant",
      "Data Transfer Request",
      "Data Transfer Data",
      "Formatted Variable Send",
      "Formatted Variable Ack",
      "Event Report Send",
      "Event Report Ack",
      "Annotated Event Report Send",
      "Annotated Event Report Ack",
      "Event Report Request",
      "Event Report Data",
      "Annotated Event Report Request",
      "Annotated Event Report Data",
      "Individual Report Request",
      "Individual Report Data",
      "Annotated Individual Report Request",
      "Annotated Individual Report Data",
      "Request or Purge Spooled Data",
      "Request or Purge Spooled Data Ack",
      "Notification Report Send",
      "Notification Report Send Ack",
      "Trace Report Send",
      "Trace Report Send Ack",
      "Trace Report Request",
      "Trace Report Data",
    ],

    // S7 - Process Program Management
    [
      "Abort Transaction",
      "Process Program Load Inquire",
      "Process Program Load Grant",
      "Process Program Send",
      "Process Program Send Acknowledge",
      "Process Program Request",
      "Process Program Data",
      "Process Program ID Request",
      "Process Program ID Data",
      "Matl/Process Matrix Request",
      "Matl/Process Matrix Data",
      "Matl/Process Matrix Update Send",
      "Matl/Process Matrix Update Ack",
      "Matl/Process Matrix Delete Entry Send",
      "Delete Matl/Process Matrix Entry Acknowledge",
      "Matrix Mode Select Send",
      "Matrix Mode Select Ack",
      "Delete Process Program Send",
      "Delete Process Program Acknowledge",
      "Current Process Program Dir Request",
      "Current Process Program Data",
      "Process Capabilities Request",
      "Process Capabilities Data",
      "Formatted Process Program Send",
      "Formatted Process Program Acknowledge",
      "Formatted Process Program Request",
      "Formatted Process Program Data",
      "Process Program Verification Send",
      "Process Program Verification Acknowledge",
      "Process Program Verification Inquire",
      "Process Program Verification Grant",
      "Verification Request Send",
      "Verification Request Acknowledge",
      "Process Program Available Request",
      "Process Program Availability Data",
      "Process Program for MID Request",
      "Process Program for MID Data",
      "Large PP Send",
      "Large PP Send Ack",
      "Large Formatted PP Send",
      "Large Formatted PP Ack",
      "Large PP Req",
      "Large PP Req Ack",
      "Large Formatted PP Req",
      "Large Formatted PP Req Ack",
    ],

    // S8 - Control Prog Xfer
    [
      "Abort Transaction",
      "Boot Program Request",
      "Boot Program Data",
      "Executive Program Request",
      "Executive Program Data",
    ],

    // S9 - Errors
    [
      "Abort Transaction",
      "Unknown Device ID",
      "",
      "Unknown Stream",
      "",
      "Unknown Function",
      "",
      "Illegal Data",
      "",
      "Transaction Timeout",
      "",
      "Data Too Long",
      "",
      "Conversation Timeout",
    ],

    // S10 - Terminal Services
    [
      "Abort Transaction",
      "Terminal Request",
      "Terminal Request Acknowledge",
      "Terminal Display, Single",
      "Terminal Display, Single Acknowledge",
      "Terminal Display, Mutli-Block",
      "Terminal Display, Multi-Block Acknowledge",
      "Multi-block Not Allowed",
      "",
      "Broadcast",
      "Broadcast Acknowledge",
    ],

    // S11 - File Management (Deleted)
    [
      "File Transaction Abort",
      "File Access Inquire",
      "File Access Grant",
      "File Write",
      "File Write Acknowledge",
      "File Read Request",
      "File Read Data",
      "File Close",
      "",
      "File Delete",
      "",
      "File Directory Request",
      "File Directory Data",
      "File Exist?",
      "File Length Data",
    ],

    // S12 - Wafer Maps
    [
      "Abort Transaction",
      "Map Setup Data Send",
      "Map Setup Data Acknowledge",
      "Map Setup Data Request",
      "Map Setup Data",
      "Map Transmit Inquire",
      "Map Transmit Grant",
      "Map Data Send Type 1",
      "Map Data Ack Type 1",
      "Map Data Send Type 2",
      "Map Data Ack Type 2",
      "Map Data Send Type 3",
      "Map Data Ack Type 3",
      "Map Data Request Type 1",
      "Map Data Type 1",
      "Map Data Request Type 2",
      "Map Data Type 2",
      "Map Data Request Type 3",
      "Map Data Type 3",
      "Map Error Report Send",
    ],

    // S13 - Dataset Transfers
    [
      "Abort Transaction",
      "Send Data Set Send",
      "Send Data Set Ack",
      "Open Data Set Request",
      "Open Data Set Data",
      "Read Data Set Request",
      "Read Data Set Data",
      "Close Data Set Send",
      "Close Data Set Ack",
      "Reset Data Set Send",
      "Reset Data Set Ack",
      "Data Set Obj Multi-Block Inquire",
      "Data Set Obj Multi-Block Grant",
      "Table Data Send",
      "Table Data Ack",
      "Table Data Request",
      "Table Data",
    ],

    // S14 - Object Services
    [
      "Abort Transaction",
      "Get Attributes",
      "Attribute Data",
      "Set Attributes",
      "Set Attributes Reply",
      "Get Type",
      "Type Data",
      "Get Attribute Names",
      "Attribute Names",
      "Create Obj Request",
      "Create Obj Ack",
      "Delete Obj Request",
      "Delete Obj Ack",
      "Object Attach Request",
      "Object Attach Ack",
      "Attached Obj Action Req",
      "Attached Obj Action Ack",
      "Supervised Obj Action Req",
      "Supervised Obj Action Ack",
      "Generic Service Req",
      "Generic Service Ack",
      "Generic Service Completion",
      "Generic Service Comp Ack",
      "Multi-block Generic Service Inquire",
      "Multi-block Generic Service Grant",
      "Service Name Request",
      "Service Name Data",
      "Service Parameter Name Req",
      "Service Parameter Name Data",
    ],

    // S15 - Recipe Management
    [
      "Abort Transaction",
      "Recipe Management MBI",
      "Recipe Management MBI Grant",
      "Recipe Namespace Action Req",
      "Recipe Namespace Action",
      "Recipe Namespace Rename Req",
      "Recipe Namespace Rename Ack",
      "Recipe Space Req",
      "Recipe Space Ack",
      "Recipe Status Request",
      "Recipe Status Data",
      "Recipe Version Request",
      "Recipe Version Data",
      "Recipe Create Req",
      "Recipe Create Ack",
      "Recipe Store Req",
      "Recipe Store Ack",
      "Recipe Retrieve Req",
      "Recipe Retrieve Data",
      "Recipe Rename Req",
      "Recipe Rename Ack",
      "Recipe Action Req",
      "Recipe Action Ack",
      "Recipe Descriptor Req",
      "Recipe Descriptor Data",
      "Recipe Parameter Update Req",
      "Recipe Parameter Update Ack",
      "Recipe Download Req",
      "Recipe Download Ack",
      "Recipe Verify Req",
      "Recipe Verify Ack",
      "Recipe Unload Req",
      "Recipe Unload Data",
      "Recipe Select Req",
      "Recipe Select Ack",
      "Recipe Delete Req",
      "Recipe Delete Ack",
      "DRNS Segment Approve Action Req",
      "DRNS Segment Approve Action Ack",
      "DRNS Recorder Seg Req",
      "DRNS Recorder Seg Ack",
      "DRNS Recorder Mod Req",
      "DRNS Recorder Mod Ack",
      "DRNS Get Change Req",
      "DRNS Get Change Ack",
      "DRNS Mgr Seg Aprvl Req",
      "DRNS Mgr Seg Aprvl Ack",
      "DRNS Mgr Rebuild Req",
      "DRNS Mgr Rebuild Ack",
      "Large Recipe Download Req",
      "Large Recipe Download Ack",
      "Large Recipe Upload Req",
      "Large Recipe Upload Ack",
      "Recipe Verification Send",
      "Recipe Verification Ack",
    ],

    // S16 - Processing Management
    [
      "Abort",
      "Process Job Data MBI",
      "PJD MBI Grant",
      "Process Job Create Req",
      "Process Job Create Ack",
      "Process Job Cmd Req",
      "Process Job Cmd Ack",
      "Process Job Alert Notify",
      "Process Job Alert Cfm",
      "Process Job Event Notify",
      "Process Job Event Cfm",
      "PRJobCreateEnh",
      "PRJobCreateEnh Ack",
      "PRJobDuplicateCreate",
      "PRJobDuplicateCreate Ack",
      "PRJobMultiCreate",
      "PRJobMultiCreate Ack",
      "PRJobDequeue",
      "PRJobDequeue Ack",
      "PRJob List Req",
      "PRJob List Data",
      "PRJob Create Limit Req",
      "PRJob Create Limit Data",
      "PRJob Recipe Variable Set",
      "PRJob Recipe Variable Ack",
      "PRJob Start Method Set",
      "PRJob Start Method Ack",
      "Control Job Command",
      "Control Job Command Ack",
      "PRSetMtrlOrder",
      "PRSetMtrlOrder Ack",
    ],

    // S17 - Per Module Reports/Event Tracing
    [
      "Abort",
      "Data Report Create Req",
      "Data Report Create Ack",
      "Data Report Del Req",
      "Data Report Del Ack",
      "Trace Create Req",
      "Trace Create Ack",
      "Trace Delete Req",
      "Trace Delete Ack",
      "Collection Event Link Req",
      "Collection Event Link Ack",
      "Collection Event Unlink",
      "Collection Event Unlink Ack",
      "Trace Reset Req",
      "Trace Reset Ack",
    ],

    // S18 - Subsystem Management
    [
      "Abort",
      "Read Attribute Req",
      "Read Attribute Data",
      "Write Attribute Req",
      "Write Attribute Ack",
      "Read Request",
      "Read Data",
      "Write Data Request",
      "Write Data Ack",
      "Read ID Req",
      "Read ID Data",
      "Write ID Req",
      "Write ID Ack",
      "Subsystem Command",
      "Subsystem Command Ack",
      "Read 2D Code Cond Req",
      "Read 2D Code Cond Data",
    ],

    // S19 - Recipes & Parameters
    [
      "Abort",
      "Get PDE Directory",
      "PDE Directory Data",
      "Delete PDE",
      "Delete PDE Ack",
      "Get PDE Header",
      "PDE Header Data",
      "Get PDE",
      "PDE Data",
      "Request to Send PDE",
      "Send PDE Grant",
      "Send PDE",
      "Send PDE Ack",
      "PDE Transfer Report",
      "Transfer Report Ack",
      "Resolve PDE Request",
      "Resolve PDE Data",
      "Verify PDE",
      "Verification Data",
      "Multiblock Inquire",
      "Multiblock Grant",
    ],

    // S20 - E170 Recipe Management
    [
      "",
      "SetSRO Attributes Request",
      "SetSRO Attributes Ack",
      "GetOperationIDList Request",
      "GetOperationIDList Ack",
      "OpenConnectionEvent Send",
      "OpenConnectionEvent Ack",
      "CloseConnectionEvent Send",
      "CloseConnectionEvent Ack",
      "ClearOperation Request",
      "ClearOperation Ack",
      "GetRecipeXIDList Request",
      "GetRecipeXIDList Ack",
      "DeleteRecipe Request",
      "DeleteRecipe Ack",
      "WriteRecipe Request",
      "WriteRecipe Ack",
      "ReadRecipe Request",
      "ReadRecipe Ack",
      "QueryRecipeXIDList Event Send",
      "QueryRecipeXIDList Event Ack",
      "QueryRecipe Event Send",
      "QueryRecipe Event Ack",
      "PostRecipe Event Send",
      "PostRecipe Event Ack",
      "SetPRC Attributes Request",
      "SetPRC Attributes Ack",
      "PreSpecifyRecipe Request",
      "PreSpecifyRecipe Ack",
      "QueryPJRecipeXIDList Event Send",
      "QueryPJRecipeXIDList Event Ack",
      "Pre-Exe Check Event Send",
      "Pre-Exe Check Event Ack",
      "PreSpecifyRecipe Event Send",
      "PreSpecifyRecipe Event Ack",
    ],

    // S21 - Item Transfer
    [
      "",
      "Item Load Inquire",
      "Item Load Grant",
      "Item Send",
      "Item Send Ack",
      "Item Request",
      "Item Data",
      "Item Type List Request",
      "Item Type List Result",
      "Supported Item Type List Request",
      "Supported Item Type List Result",
      "Item Delete",
      "Item Delete Ack",
      "Request Send Permission",
      "Grant Send Permission",
      "Item Request",
      "Item Request Grant",
      "Send Item Part",
      "Send Item Part Ack",
      "Item Type Support Query",
      "Item Type Support Result",
    ],
  ];
}
